version: '3.3'

services:
    pgvector_db:
        image: pgvector/pgvector:pg16
        container_name: pgvector_db
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: admin # Change this to your desired password
            POSTGRES_USER: admin # Change this to your desired user name
            POSTGRES_DB: admin # Change this to your desired database name
        volumes:
            - pgvector_data:/var/lib/postgresql/data

volumes:
    pgvector_data:
